---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- üçø Media:
        - Movies:
                icon: sh-radarr.webp
                href: "https://radarr.${SECRET_DOMAIN}"
                widget:
                      type: radarr
                      url: http://radarr.default.svc:8787
                      key: "${RADARR_API_TOKEN}"
        - TV:
                icon: sh-sonarr.webp
                href: "https://sonarr.${SECRET_DOMAIN}"
                widget:
                      type: sonarr
                      url: http://sonarr.default.svc:8787
                      key: "${SONARR_API_TOKEN}"
        - SABnzbd:
                icon: sh-sabnzbd.webp
                href: "http://vault.local:30055/apps/sabnzbd/"
                widget:
                      type: sabnzbd
                      url: http://192.168.86.200:30055/apps/sabnzbd/
                      key: "${SABNZBD_API_KEY}"
- üè° Smart Home:
        - Home Assistant:
                icon: sh-home-assistant.webp
                href: "http://192.168.86.212:8123/lovelace-hjbjhbjh/0"
        - ESPHome:
                icon: sh-esphome.webp
                href: "https://esphome.${SECRET_DOMAIN}"
        - App Daemon:
                icon: sh-daemon-sync.webp
                href: "https://appdaemon.${SECRET_DOMAIN}"

- ü§ì Nerd Stuff:
        - Grafana:
                icon: sh-grafana.webp
                href: "https://grafana.${SECRET_DOMAIN}"
        - Rook:
                icon: sh-ceph.webp
                href: "https://rook.${SECRET_DOMAIN}"
        - Alertmanager:
                icon: sh-prometheus.webp
                href: "https://alertmanager.${SECRET_DOMAIN}"
