---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings

title: "ğŸ  ${SECRET_DOMAIN} Homepage"
headerStyle: clean
layout:
  ğŸ¿ Media:
    style: row
    columns: 3
