apiVersion: v1
kind: Secret
metadata:
    name: homepage-secrets
stringData:
    SONARR_API_TOKEN: ENC[AES256_GCM,data:fAwV0jioEz8oHVBWZ0fhlej5T8EObK94LRzFedq8NSE=,iv:884LzPPfBGv7yzrr8QCUIlH6yAaKoF9Pba2+7O2Ssjw=,tag:m6c9hC7NQc7APK3TYcmDfw==,type:str]
    RADARR_API_TOKEN: ENC[AES256_GCM,data:3gV4ppIvfSmGc/Si4LU+f0wr6Z/8XF1hyKopu4aDvng=,iv:lT9bSqfbjaCW8D2LwlfoJgDWz1BtFfRWZ4cY5A21nlo=,tag:xxLopjoIlOrZcsxdoKwhjA==,type:str]
    SABNZBD_API_KEY: ENC[AES256_GCM,data:Ha/djuVgqxPlQo33AaJaqPCkZnycHpBxr0fjis9uziY=,iv:+zHys4qJv7w+8oAr+ZQjitJaDhnAyUk2BLhHeSm8OzQ=,tag:YGVaAGiVvicA6V7xxpM8uQ==,type:str]
sops:
    age:
        - recipient: age1fa4w3h22pca5exw0z2hsa0syu4kley69l722gupsnnhhz76a6sqst2wgyl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGdlZ6S2pOUXg3VG50NnVq
            TFV1WTNsWlRGYk5nT3BoU0dKbUhiMEJLQm1zCkh3UkZSdUgzVmk0SENYYVNLbVg4
            bEZhZnpya01SMUZiT2U3RWQvZXRGZ00KLS0tIERTMkcrVGxPUXNLVzdic2ZSYUpj
            WWg0UGtSQTBNakRpZERjSlhmeGdOOU0KtbP7r50umuxzurfD54a+EtxH+rtSPOHj
            kQOt6nmr1cRGSi23pYzuyb9ABcjMcYrtK0/mdfP3F/+5acPUOoY/7A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-13T23:37:06Z"
    mac: ENC[AES256_GCM,data:VqsOMwX8v+HOAkeKb95t25/W5htwGYI79GrEHulF1LxE1WLrCYxcP/EARFTzweWNRlqBlpfdQL7rleqaYffcr7qJYxLIMXtApXYJ5o8r3MH8sfOtF8C9L1KDVBRg2gCIc+1J/vMfeeGwLV7efHM02ODcdUfVDC8K/HT8lIIDnl0=,iv:79s55F9dgDO5EHYQDVHpjMwg73/lpyNcRXBWaqV0Bzk=,tag:pYe6gzpWm9u37cstlABRvA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
